2semestre/2semestre/Controllers/DivulgacaoController.cs
using Agroconnect_Login.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Agroconnect_Login.Controllers
{
    public class DivulgacoesController : Controller
    {
       

        public IActionResult Produto()
        {
            return View();
        }

        public IActionResult Maquina()
        {
            return View();
        }

        public IActionResult Servico()
        {
            return View();
        }
    }
}

2semestre/2semestre/Controllers/LoginController.cs
using Agroconnect_Login.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Agroconnect_Login.Controllers
{
    public class LoginController : Controller
    {
      

        public IActionResult Perfil()
        {
            return View();
        }

        public IActionResult Editar()
        {
            return View();
        }

        public IActionResult Criar()
        {
            return View();
        }

    }
}

2semestre/2semestre/Controllers/PublicacaoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
//using NuGet.Protocol.Core.Types; //TA VERMELHO SUBLINHADO
using Agroconnect_Login.Models;
using Agroconnect_Login.Repositories.ADO.SQLServer;

namespace Agroconnect_Login.Controllers
{
    public class PublicacaoController : Controller
    {


        private readonly Repositories.ADO.SQLServer.PublicacaoDAO repository;


        // objeto configuration => parte do framework que permite ler o
        // arquivo appsettings.json - GetConnectionString => método do framework que permite
        // ler a chave ConnectionStrings deste arquivo.
        public PublicacaoController(IConfiguration configuration)
        {
            this.repository = new Repositories.ADO.SQLServer.PublicacaoDAO(configuration.GetConnectionString(Configurations.Appsettings.getKeyConnectionString()));
            //Configurations.Appsettings.getKeyConnectionString => nossa classe de configuração para trazer a chave que
            //deve ser lida, neste caso: DefaultConnection.
        }

        // GET => getAll: CarrosController
        [HttpGet]
        public IActionResult Index()
        {
            return View(this.repository.getAll());
        }

        // GET => getByIdCarro(id): CarrosController/Edit/5
        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(this.repository.getByIdPublicacao(id));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Publicacao publicacao)
        {
            try
            {
                this.repository.update(id, publicacao);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }









        // GET : CarrosController/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST : CarrosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Publicacao publicacao)
        {
            try
            {
                this.repository.add(publicacao);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET : CarrosController/Details/5
        //[HttpGet]
        //public IActionResult Details(int id)
        //{
        //    //return View(this.repository.getByIdPublicacao(id));
        //    //    return View(this.repository.getByIdCarro(id));
        //}

        // GET : CarrosController/Delete/5
        [HttpGet]
        public IActionResult Delete(int id)
        {
            this.repository.delete(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

2semestre/2semestre/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agroconnect_Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/perfil.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Agroconnect_Login.styles.css" asp-append-version="true" />
</head>
<body>
    <header id="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand"  asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo.png" alt="Logo" width="130" height="60" class="d-inline-block align-text-top" >
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Agroconnect</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                       <!--<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>--> 

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Divulgações por Categorias
                            </a>
                            <div class="dropdown-menu bg-light" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="Divulgacoes" asp-action="Produto">Produtos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Divulgacoes" asp-action="Maquina">Máquinas</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Divulgacoes" asp-action="Servico">Serviços</a>
                            </div>
                        </li>
                 
                    </ul>
                      <div class="flex-container">
                   <input type="text" id="filtro" placeholder="Digite para filtrar">
                   <div>
                       <div class="pesquisaC">
                        <div class="item" data-titulo="Baldan">
                            <img src="~/img/LogoBaldan.png" alt="Ícone 1" class="icone" />
                            <a asp-area="" asp-controller="Publicacao" asp-action="Index"> Baldan </a></div>

                            <div class="item" data-titulo="Bella Vista">
                                <img src="https://static.vecteezy.com/system/resources/previews/017/628/444/original/letter-b-agriculture-logo-and-farming-logo-symbol-design-free-vector.jpg" alt="Ícone 1" class="icone" />
                                <a asp-area="" asp-controller="Home" asp-action="Solpoente"> Bella Vista </a>
                            </div>

                        <div class="item" data-titulo="Sol Poente">
                            <img src="https://blog4.mfrural.com.br/wp-content/uploads/2020/08/fazenda-venda3.jpg" alt="Ícone 1" class="icone" />
                            <a asp-area="" asp-controller="Login" asp-action="Perfil"> Sol Poente </a></div>
                    </div>
                    </div>
                    </div>
                    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
                    <partial name="_LoginPartial" />
                </div>
            </div>
           
        </nav>
    </header>
    <div >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    
</body>


</html>